TST-info-based-on-CBOR-time-tag = {
  &(version : 0) => v1
  &(policy : 1) => oid
  &(messageImprint : 2) => MessageImprint
  &(serialNumber : 3) => integer
  &(eTime : 4) => profiled-etime
  ? &(ordering : 5) => bool .default false
  ? &(nonce : 6) => integer
  ? &(tsa : 7) => SingleEntryGeneralNames
  * $$TSTInfoExtensions
}

v1 = 1

oid = #6.111(bstr) / #6.112(bstr)

MessageImprint = [
  hashAlg : int
  hashValue : bstr
]

profiled-etime = #6.1001(timeMap)
timeMap = {
  1 => int / float ; TIME_T
  ? -8 => profiled-duration
  * int => any
}
profiled-duration = {* int => any}

GeneralName = ( GeneralNameType : int, GeneralNameValue : any )
SingleEntryGeneralNames = [ 1*1 GeneralName ]
